server:
  port: 30003   #端口号
eureka:
  client:
    service-url:
      defaultZone: http://localhost:30001/eureka/  #注册中心地址
    registry-fetch-interval-seconds: 5    #修改缓存清单的更新时间
spring:
  application:
    name: test-service   #注册到服务中心的名称
