server:
  port: 30002  #端口号
eureka:
  client:
    service-url:
      defaultZone: http://localhost:30001/eureka/  #注册中心地址
    registry-fetch-interval-seconds: 5   #修改缓存清单的更新时间
spring:
  application:
    name: qt-service  #注册到服务中心的名称
#连接redis数据库
  redis:
    host: 127.0.0.1    #数据库地址
    port: 6379       #数据库端口号
    database: 0        #数据库名称
    password: 123456    #数据库密码
    jedis:
      pool:
        max-active: 50    #最大连接数
        max-wait: 3000ms   #最长连接时间
        min-idle: 2
        max-idle: 20
    connect-timeout: 5000ms
#开启feign熔断器，默认是开启的，可以不用配置
feign:
  hystrix:
    enabled: true